return {
    -- {
    --     "lukas-reineke/indent-blankline.nvim",
    --     main = "ibl",
    --     config = function()
    --         local highlight = {
    --             "RainbowRed",
    --             "RainbowYellow",
    --             "RainbowBlue",
    --             "RainbowOrange",
    --             "RainbowGreen",
    --             "RainbowViolet",
    --             "RainbowCyan",
    --         }
    --         vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
    --         vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
    --         vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
    --         vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
    --         vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
    --         vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
    --         vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
    --
    --         vim.g.rainbow_delimiters = { highlight = highlight }
    --         require("ibl").setup {
    --             indent = {
    --                 highlight = highlight,
    --                 char = '│',
    --             }
    --         }
    --     end
    -- },
    -- {
    --     "HiPhish/rainbow-delimiters.nvim",
    --     config = function()
    --         require('rainbow-delimiters.setup').setup {
    --             strategy = {
    --                 -- ...
    --             },
    --         }
    --     end
    -- }
}
