#!/usr/bin/env bash

monitors=$(hyprctl monitors -j)

echo "$monitors" | jq -r '.[] | select(not(.name | startswith("eDP") or startswith("LVDS") or startswith("WAYLAND"))) | .description' | while read -r desc; do
  hyprctl keyword monitor "$desc, preferred, auto, 1, transform, 3"
done
