#!/usr/bin/env bash

if [[ -z "$WAYLAND_DISPLAY" || "$WAYLAND_DISPLAY" == "wayland-0" ]]; then
  echo "No display!"
fi

monitors=$(hyprctl monitors -j)

echo "$monitors" | jq -r '.[] | select((.name | startswith("eDP") or startswith("LVDS") or startswith("WAYLAND")) | not) | .description' | while read -r desc; do
  hyprctl keyword monitor "$desc, preferred, auto, 1, transform, 3"
done
