#!/usr/bin/env bash

if [[ -z "$WAYLAND_DISPLAY" || "$WAYLAND_DISPLAY" == "wayland-0" ]]; then
  echo "No display!"
fi

hyprctl monitors -j | jq -r '.[] | select((.name | startswith("eDP") or startswith("LVDS") or startswith("WAYLAND")) | not) | "\(.description)|\(.scale)"' | while IFS='|' read -r desc scale; do
  hyprctl keyword monitor "desc:$desc, preferred, auto, $scale, transform, 3"
done
