#!/usr/bin/env bash

if [[ -z "$WAYLAND_DISPLAY" || "$WAYLAND_DISPLAY" == "wayland-0" ]]; then
  echo "No display!"
fi

# Get the address of the currently active window
active_addr=$(hyprctl activewindow -j | jq -r '.address')

# Get all window addresses
hyprctl clients -j | jq -r '.[].address' | while read -r addr; do
  if [ "$addr" != "$active_addr" ]; then
    hyprctl dispatch closewindow address:"$addr"
  fi
done

# Return the address of the currently active window
echo "$active_addr"
